import {CalendarIcon} from '@mui/x-date-pickers';
import {FaPeopleGroup} from 'react-icons/fa6';
import {SlCalender} from 'react-icons/sl';
import {TfiTime} from 'react-icons/tfi';
import {CiMobile3} from 'react-icons/ci';
import {FaAngleDown} from 'react-icons/fa6';
import {FaAngleUp} from 'react-icons/fa6';
import {RxCross2} from 'react-icons/rx';
import {LiaPhoneAltSolid} from 'react-icons/lia';
import {GrMap} from 'react-icons/gr';
import {PiTagLight} from 'react-icons/pi';
import {HiOutlineLink} from 'react-icons/hi2';
import {FcGoogle} from 'react-icons/fc';
import {BsFacebook} from 'react-icons/bs';
import {FaApple} from 'react-icons/fa';
import {IoRestaurant} from 'react-icons/io5';
import {CgProfile} from 'react-icons/cg';
import {FaFacebookF} from 'react-icons/fa';
import {FaLinkedinIn} from 'react-icons/fa';
import {FaXTwitter} from 'react-icons/fa6';
import {TfiTimer} from 'react-icons/tfi';
import {CiCalendar} from 'react-icons/ci';
import {AiTwotoneThunderbolt} from 'react-icons/ai';
import {CiEdit} from 'react-icons/ci';
import {AiOutlineDelete} from 'react-icons/ai';
import {IoDuplicateOutline} from 'react-icons/io5';
import {CiMenuKebab} from 'react-icons/ci';
import {GoComment} from 'react-icons/go';
import {FaPlaneArrival} from 'react-icons/fa';
import {FaUserCheck} from 'react-icons/fa';
import {FiUserPlus} from 'react-icons/fi';
import {CiMenuFries} from 'react-icons/ci';
import {RiMenuAddFill} from 'react-icons/ri';

export const Calendar = CalendarIcon;
export const People = FaPeopleGroup;
export const Date = SlCalender;
export const Time = TfiTime;
export const Mobile = CiMobile3;
export const DownArrow = FaAngleDown;
export const Cross = RxCross2;
export const UpArrow = FaAngleUp;
export const Phone = LiaPhoneAltSolid;
export const Map = GrMap;
export const Tag = PiTagLight;
export const WebLink = HiOutlineLink;
export const Google = FcGoogle;
export const Facebook = BsFacebook;
export const Apple = FaApple;
export const Restaurant = IoRestaurant;
export const Profile = CgProfile;
export const FooterFacebook = FaFacebookF;
export const FooterLinkedin = FaLinkedinIn;
export const FooterTwitter = FaXTwitter;
export const Timer = TfiTimer;
export const Calendar2 = CiCalendar;
export const Status = AiTwotoneThunderbolt;
export const Edit = CiEdit;
export const Delete = AiOutlineDelete;
export const Duplicate = IoDuplicateOutline;
export const VerticalMenu = CiMenuKebab;
export const Comments = GoComment;
export const NearBy = FaPlaneArrival;
export const SignIn = FaUserCheck;
export const SignUp = FiUserPlus;
export const Menu = CiMenuFries;
export const OptionMenu = RiMenuAddFill;
